### PR TITLE
Add pass-through publish task and disable shouldPublishJars

### PR DESCRIPTION
**Pull request by jeremyjams**

### CODE REVIEW

**Review by mcornaton — APPROVED** [review]
Thanks!

**Review by jbern0rd — COMMENTED** [review]
This won't work.
The `publishing` block is entirely missing in `build.gradle`.

See `iexec-common` configuration

```
publishing {
    publications {
        maven(MavenPublication) {
            from components.java
        }
    }
    repositories {
        maven {
            credentials {
                username project.hasProperty('nexusUser') ? nexusUser : ''
                password project.hasProperty('nexusPassword') ? nexusPassword : ''
            }
            url = project.hasProperty('nexusUrl') ? nexusUrl : ''
        }
    }
}
```

**Comment by jeremyjams** [comment]
> This won't work. The `publishing` block is entirely missing in `build.gradle`.
> 
> See `iexec-common` configuration
> 
> ```
> publishing {
>     publications {
>         maven(MavenPublication) {
>             from components.java
>         }
>     }
>     repositories {
>         maven {
>             credentials {
>                 username project.hasProperty('nexusUser') ? nexusUser : ''
>                 password project.hasProperty('nexusPassword') ? nexusPassword : ''
>             }
>             url = project.hasProperty('nexusUrl') ? nexusUrl : ''
>         }
>     }
> }
> ```

Build work, we don't need the JAR, but let's stay consistent by publishing it :+1:

**Review by zguesmi — APPROVED** [review]

**Comment by mcornaton** [comment]
If we don't need the JAR, why do we set `shouldPublishJars: true`?

**Comment by jeremyjams** [comment]
> If we don't need the JAR, why do we set `shouldPublishJars: true`?
Some copy/paste, JAR haven't been ever published

**Comment by jbern0rd** [comment]
> > This won't work. The `publishing` block is entirely missing in `build.gradle`.
> > See `iexec-common` configuration
> > ```
> > publishing {
> >     publications {
> >         maven(MavenPublication) {
> >             from components.java
> >         }
> >     }
> >     repositories {
> >         maven {
> >             credentials {
> >                 username project.hasProperty('nexusUser') ? nexusUser : ''
> >                 password project.hasProperty('nexusPassword') ? nexusPassword : ''
> >             }
> >             url = project.hasProperty('nexusUrl') ? nexusUrl : ''
> >         }
> >     }
> > }
> > ```
> 
> Build work, we don't need the JAR, but let's stay consistent by publishing it +1

Thanks for the explanation.
As discussed, it will become interesting to review what we publish for each kind of project now that we have application projects and library projects.
But we can do this later. Right now, it is more important to release a new version.
Thanks for the fix !

**Review by jbern0rd — APPROVED** [review]

**Review by mcornaton — APPROVED** [review]

**Comment by jeremyjams** [comment]
> If we don't need the JAR, why do we set `shouldPublishJars: true`?

Thanks for the reminder @mcornaton, here is https://github.com/iExecBlockchainComputing/tee-worker-post-compute/pull/39/commits/1b14139b0f82901fc3c73753144b89449a57bb4d "publishing can be activated safely but currently disabled". Still needs discussions on what we want, but our release flow can carry-on with that.

**Pull request merged**
